CREATE TABLE IF NOT EXISTS tareas (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  titulo TEXT NOT NULL,
  completado INTEGER NOT NULL DEFAULT 0 CHECK (completado IN (0,1)),
  created_at DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);
